apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
      - name: [AWS_REGION]-ecr-registry
      containers:
        - image: [AWS_ACCOUNT_ID].dkr.ecr.ap-south-1.amazonaws.com/demo:latest
          name: web
          envFrom:
            - configMapRef:
                name: config-map
          ports:
            - name: backend-port
              containerPort: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
