kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: razorops-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: razorops
    namespace: default
roleRef:
  kind: Role
  name: razorope-role
  apiGroup: rbac.authorization.k8s.io
