kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: razorops-role
  namespace: default
rules:
  - apiGroups: ["", "apps", "batch", "extensions"]
    resources: ["deployments", "services", "replicasets", "pods", "jobs", "cronjobs", "secrets", "serviceaccounts"]
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
